### ISSUE TITLE
android 随机崩溃的问题

### ISSUE THREAD

**Issue by yanerzhao** [chukong/quick-cocos2d-x#376]
目前在android平台（IOS和Windows并未大面积测试，尚未遇到），会发现有quick随机崩溃的问题，崩溃十分随机，有时玩15分钟会崩溃，有时4,5个小时也不会崩溃，拿到的tombstone文件里，崩溃栈都比较乱，但大概都是内存释放的错误。无法定位具体问题所在，但崩溃的动作基本一致：在removeUnusedSpriteFrames()，purgeCachedData进行内存清理之后，隔一帧再创建一个占内存比较大和比较复杂Layer附近,会非常偶然的发生崩溃，使用方式已查找多次，除材质较多面板内存较大，没有特殊用法。
但是在一些崩溃信息里，能看到或许与lua有关的一些信息。
1.在一个aaa:setDisplayFrame(CCSprite:create("xx.png"):displayFrame())的函数里，有效概率会出现diplayFrame的调用到了shortcodes.lua里的CCSpriteExtend.displayFrame()函数，但代码中并没有用CCSpritExtend扩展对象，应该是tolua在调用时错乱导致的问题。
2.一些崩溃点是内存被重复释放或偶尔CCASERT(reference > 0)失败，而这些对象会是lua里被索引过。
如果有谁遇到类似问题能帮到的话，非常感谢。

以下是一些崩溃的例子：
============================例1========================
backtrace:
    #00  pc 001c103a  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCComponentContainer::removeAll()+11)
    #01  pc 00185541  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCNode::~CCNode()+224)
    #02  pc 001b536f  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCSprite::~CCSprite()+78)
    #03  pc 001b5395  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCSprite::~CCSprite()+4)
    #04  pc 001888a3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+86)
    #05  pc 001bb5b9  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayRemoveAllObjects(cocos2d::_ccArray_)+16)
    #06  pc 001bb5cf  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayFree(cocos2d::_ccArray_&)+10)
    #07  pc 00189215  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+16)
    #08  pc 0018922d  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+4)
    #09  pc 001888a3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+86)
    #10  pc 00185533  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCNode::~CCNode()+210)
    #11  pc 00199203  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+58)
    #12  pc 001993b1  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+4)
    #13  pc 001888a3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+86)
    #14  pc 001bb5b9  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayRemoveAllObjects(cocos2d::_ccArray_)+16)
    #15  pc 001bb5cf  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayFree(cocos2d::_ccArray_&)+10)
    #16  pc 00189215  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+16)
    #17  pc 0018922d  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+4)
    #18  pc 001888a3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+86)
    #19  pc 00185533  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCNode::~CCNode()+210)
    #20  pc 00199203  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+58)
    #21  pc 001993b1  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+4)
    #22  pc 001888a3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+86)
    #23  pc 001bb5b9  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayRemoveAllObjects(cocos2d::_ccArray_)+16)
    #24  pc 001bb5cf  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayFree(cocos2d::_ccArray_&)+10)
    #25  pc 00189215  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+16)
    #26  pc 0018922d  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+4)
    #27  pc 001888a3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+86)
    #28  pc 00185533  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCNode::~CCNode()+210)
    #29  pc 00199203  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+58)
    #30  pc 001993b1  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+4)
    #31  pc 001888a3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+86)

stack:
         7349a930  76e2c1c0  
         7349a934  76e5f910  
         7349a938  00000001  
         7349a93c  7e742d18  
         7349a940  7e742e14  
         7349a944  0000020c  
         7349a948  00000001  
         7349a94c  72e36a91  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLuaStack::removeScriptObjectByCCObject(cocos2d::CCObject_)+10)
         7349a950  72e36a87  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLuaStack::removeScriptObjectByCCObject(cocos2d::CCObject_))
         7349a954  72e35a37  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLuaEngine::removeScriptObjectByCCObject(cocos2d::CCObject_)+10)
         7349a958  72e35a2d  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLuaEngine::removeScriptObjectByCCObject(cocos2d::CCObject_))
         7349a95c  72dbc7f9  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::~CCObject()+84)
         7349a960  732428f0  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so
         7349a964  7e742d18  
         7349a968  df0027ad  
         7349a96c  00000000  
    #00  7349a970  72df502f  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCComponentContainer::removeAll())
         7349a974  7df607a0  
         7349a978  7df6089c  
         7349a97c  00000000  
         7349a980  00000001  
         7349a984  72db9543  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCNode::~CCNode()+226)
    #01  7349a988  00000170  
         7349a98c  7df607a0  
         7349a990  7d0fdfe0  
         7349a994  72de9373  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCSprite::~CCSprite()+82)
    #02  7349a998  7df607a0  
         7349a99c  72de9399  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCSprite::~CCSprite()+8)
    #03  7349a9a0  7df607a0  
         7349a9a4  72dbc8a5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+88)
    #04  7349a9a8  7df607a0  
         7349a9ac  7e742df4  
         7349a9b0  7e706930  
         7349a9b4  7bc0d888  
         7349a9b8  7d0fdfe0  
         7349a9bc  72def5bd  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayRemoveAllObjects(cocos2d::_ccArray_)+20)
    #05  7349a9c0  7a7a576c  
         7349a9c4  72def5d3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayFree(cocos2d::_ccArray_&)+14)
    #06  7349a9c8  7a7a5758  
         7349a9cc  72dbd219  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+20)
    #07  7349a9d0  7a7a5758  
         7349a9d4  72dbd231  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+8)
    #08  7349a9d8  7a7a5758  
         7349a9dc  72dbc8a5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+88)
    #09  7349a9e0  7a7a5758  
         7349a9e4  7e742df4  
         7349a9e8  7e706974  
         7349a9ec  7d0fdf08  
         7349a9f0  7d0fdfe0  
         7349a9f4  72db9537  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCNode::~CCNode()+214)
    #10  7349a9f8  73244bfc  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so
         7349a9fc  7d0fdf08  
         7349aa00  7e6d4c10  
         7349aa04  72dcd207  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+62)
    #11  7349aa08  7d0fdf08  
         7349aa0c  72dcd3b5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+8)
    #12  7349aa10  7d0fdf08  
         7349aa14  72dbc8a5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+88)
    #13  7349aa18  7d0fdf08  
         7349aa1c  7d0fdfe4  
         7349aa20  7c71c228  
         7349aa24  7ccdb880  
         7349aa28  7e6d4c10  
         7349aa2c  72def5bd  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayRemoveAllObjects(cocos2d::_ccArray_)+20)
    #14  7349aa30  7e80675c  
         7349aa34  72def5d3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayFree(cocos2d::_ccArray_&)+14)
    #15  7349aa38  7e806748  
         7349aa3c  72dbd219  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+20)
    #16  7349aa40  7e806748  
         7349aa44  72dbd231  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+8)
    #17  7349aa48  7e806748  
         7349aa4c  72dbc8a5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+88)
    #18  7349aa50  7e806748  
         7349aa54  7d0fdfe4  
         7349aa58  7c71c228  
         7349aa5c  7e6d4b38  
         7349aa60  7e6d4c10  
         7349aa64  72db9537  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCNode::~CCNode()+214)
    #19  7349aa68  73244bfc  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so
         7349aa6c  7e6d4b38  
         7349aa70  7a7d0668  
         7349aa74  72dcd207  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+62)
    #20  7349aa78  7e6d4b38  
         7349aa7c  72dcd3b5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+8)
    #21  7349aa80  7e6d4b38  
         7349aa84  72dbc8a5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+88)
    #22  7349aa88  7e6d4b38  
         7349aa8c  76f4f344  
         7349aa90  7dedf170  
         7349aa94  7a7a3198  
         7349aa98  7a7d0668  
         7349aa9c  72def5bd  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayRemoveAllObjects(cocos2d::_ccArray_)+20)
    #23  7349aaa0  7b5a836c  
         7349aaa4  72def5d3  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayFree(cocos2d::_ccArray_&)+14)
    #24  7349aaa8  7b5a8358  
         7349aaac  72dbd219  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+20)
    #25  7349aab0  7b5a8358  
         7349aab4  72dbd231  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCArray::~CCArray()+8)
    #26  7349aab8  7b5a8358  
         7349aabc  72dbc8a5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+88)
    #27  7349aac0  7b5a8358  
         7349aac4  76f4f344  
         7349aac8  7dedf17c  
         7349aacc  7a7d0590  
         7349aad0  7a7d0668  
         7349aad4  72db9537  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCNode::~CCNode()+214)
    #28  7349aad8  73244bfc  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so
         7349aadc  7a7d0590  
         7349aae0  00000001  
         7349aae4  72dcd207  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+62)
    #29  7349aae8  7a7d0590  
         7349aaec  72dcd3b5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCLayer::~CCLayer()+8)
    #30  7349aaf0  7a7d0590  
         7349aaf4  72dbc8a5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCObject::release()+88)
    #31  7349aaf8  7a7d0590  
         7349aafc  00000000  
         7349ab00  00000000  
         7349ab04  7ccacc18  
         7349ab08  00000001  
         7349ab0c  72def655  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayRemoveObjectAtIndex(cocos2d::_ccArray_, unsigned int, bool)+108)
         7349ab10  7ccacc18  
         7349ab14  00000000  
         7349ab18  00000001  
         7349ab1c  7ccacc18  
         7349ab20  00000001  
         7349ab24  00000001  
         7349ab28  76e2cd00  
         7349ab2c  72def6dd  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::ccArrayRemoveObject(cocos2d::_ccArray_, cocos2d::CCObject_, bool)+24)
         7349ab30  00000000  
         7349ab34  7a7d0590  
============================例2========================
backtrace:
    #00  pc 000112a0  /system/lib/libc.so (dlfree+55)
    #01  pc 0000dc53  /system/lib/libc.so (free+10)
    #02  pc 00067319  /system/lib/libicuuc.so (icu_51::UnicodeSet::~UnicodeSet()+72)
    #03  pc 000baab1  /system/lib/libicui18n.so (icu_51::RegexPattern::zap()+96)
    #04  pc 000bad5d  /system/lib/libicui18n.so (icu_51::RegexPattern::~RegexPattern()+16)
    #05  pc 000132d7  /system/lib/libjavacore.so
    #06  pc 0001ea90  /system/lib/libdvm.so (dvmPlatformInvoke+116)
    #07  pc 0004f6a7  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const_, JValue_, Method const_, Thread_)+398)
    #08  pc 00027f20  /system/lib/libdvm.so
    #09  pc 0002f418  /system/lib/libdvm.so (dvmMterpStd(Thread_)+76)
    #10  pc 0002cabc  /system/lib/libdvm.so (dvmInterpret(Thread_, Method const_, JValue_)+184)
    #11  pc 00061b23  /system/lib/libdvm.so (dvmCallMethodV(Thread_, Method const_, Object_, bool, JValue_, std::__va_list)+338)
    #12  pc 00061b47  /system/lib/libdvm.so (dvmCallMethod(Thread_, Method const_, Object_, JValue_, ...)+20)
    #13  pc 00056833  /system/lib/libdvm.so
    #14  pc 0000d1c0  /system/lib/libc.so (__thread_entry+72)
    #15  pc 0000d358  /system/lib/libc.so (pthread_create+240)
============================例3========================
backtrace:
    #00  pc 00021930  /system/lib/libc.so (__futex_syscall3+8)
    #01  pc 0000e6b4  /system/lib/libc.so
    #02  pc 0000fe43  /system/lib/libc.so (dlmalloc+46)
    #03  pc 0000dc3f  /system/lib/libc.so (malloc+10)
    #04  pc 0000d529  /system/lib/libutils.so (android::SharedBuffer::alloc(unsigned int)+8)
    #05  pc 0000fcf3  /system/lib/libutils.so (android::VectorImpl::_shrink(unsigned int, unsigned int)+84)
    #06  pc 00010963  /system/lib/libutils.so (android::Looper::pollInner(int)+74)
    #07  pc 00010ba1  /system/lib/libutils.so (android::Looper::pollOnce(int, int_, int_, void__)+92)
    #08  pc 0006f0bd  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv_, int)+22)
    #09  pc 0001ea90  /system/lib/libdvm.so (dvmPlatformInvoke+116)
    #10  pc 0004f6a7  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const_, JValue_, Method const_, Thread_)+398)
    #11  pc 00027f20  /system/lib/libdvm.so
    #12  pc 0002f418  /system/lib/libdvm.so (dvmMterpStd(Thread_)+76)
    #13  pc 0002cabc  /system/lib/libdvm.so (dvmInterpret(Thread_, Method const_, JValue_)+184)
    #14  pc 00061e05  /system/lib/libdvm.so (dvmInvokeMethod(Object_, Method const_, ArrayObject_, ArrayObject_, ClassObject_, bool)+392)
    #15  pc 00069edb  /system/lib/libdvm.so
    #16  pc 00027f20  /system/lib/libdvm.so
    #17  pc 0002f418  /system/lib/libdvm.so (dvmMterpStd(Thread_)+76)
    #18  pc 0002cabc  /system/lib/libdvm.so (dvmInterpret(Thread_, Method const_, JValue_)+184)
    #19  pc 00061b23  /system/lib/libdvm.so (dvmCallMethodV(Thread_, Method const_, Object_, bool, JValue_, std::__va_list)+338)
    #20  pc 0004b287  /system/lib/libdvm.so
    #21  pc 00051b37  /system/lib/libandroid_runtime.so
    #22  pc 0005285b  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const_, char const_)+354)
    #23  pc 0000105b  /system/bin/app_process
    #24  pc 0000e393  /system/lib/libc.so (__libc_init+50)
    #25  pc 00000d7c  /system/bin/app_process
============================例4========================
backtrace:
    #00  pc 00021fbc  /system/lib/libc.so (tgkill+12)
    #01  pc 0001300f  /system/lib/libc.so (pthread_kill+50)
    #02  pc 00013207  /system/lib/libc.so (raise+10)
    #03  pc 00011f73  /system/lib/libc.so
    #04  pc 00021870  /system/lib/libc.so (abort+4)
    #05  pc 00012a45  /system/lib/libc.so
    #06  pc 0000f165  /system/lib/libc.so
    #07  pc 0001172f  /system/lib/libc.so (dlfree+1222)
    #08  pc 0000dc53  /system/lib/libc.so (free+10)
    #09  pc 004d888c  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so
    #10  pc 001b84b7  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (std::_Rb_tree<std::string, std::string, std::_Identity<std::string>, std::lessstd::string, std::allocatorstd::string >::_M_erase(std::_Rb_tree_nodestd::string_)+22)
    #11  pc 001b85d1  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCSpriteFrameCache::removeUnusedSpriteFrames()+108)
    #12  pc 00166143  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (MobileGameUtil::purgeCachedData()+6)
    #13  pc 001667eb  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so
    #14  pc 0045adc0  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so

stack:
         75c0d828  00000000  
         75c0d82c  75c0dc40  [stack:32081]
         75c0d830  00000000  
         75c0d834  75c0dc94  [stack:32081]
         75c0d838  00000000  
         75c0d83c  00000000  
         75c0d840  00000000  
         75c0d844  00000000  
         75c0d848  00000000  
         75c0d84c  00000000  
         75c0d850  00000000  
         75c0d854  00000000  
         75c0d858  00000000  
         75c0d85c  00000000  
         75c0d860  fffffff4  
         75c0d864  77d711c0  
    #00  75c0d868  75c0ddd8  [stack:32081]
         75c0d86c  00000006  
         75c0d870  00000000  
         75c0d874  00007d51  
         75c0d878  00007d51  
         75c0d87c  400cb013  /system/lib/libc.so (pthread_kill+54)
    #01  75c0d880  75c0ddd0  [stack:32081]
         75c0d884  00000006  
         75c0d888  00000000  
         75c0d88c  00000000  
         75c0d890  401061a8  
         75c0d894  400cb20b  /system/lib/libc.so (raise+14)
    #02  75c0d898  75c0d8a4  [stack:32081]
         75c0d89c  400c9f77  /system/lib/libc.so
    #03  75c0d8a0  7a74fcb8  
         75c0d8a4  ffffffdf  
         75c0d8a8  7a74fcd8  
         75c0d8ac  7a124240  
         75c0d8b0  7a124240  
         75c0d8b4  77d711c0  
         75c0d8b8  00000000  
         75c0d8bc  7d038b78  [anon:libc_malloc]
         75c0d8c0  00000000  
         75c0d8c4  400d9874  /system/lib/libc.so (__pthread_clone)
    #04  75c0d8c8  837e6def  
         75c0d8cc  400caa49  /system/lib/libc.so
    #05  75c0d8d0  400f7e43  /system/lib/libc.so
         75c0d8d4  75c0d8e4  [stack:32081]
         75c0d8d8  ffffff60  
         75c0d8dc  400c7169  /system/lib/libc.so
         75c0d8e0  400f7e43  /system/lib/libc.so
         75c0d8e4  400fb9d6  /system/lib/libc.so
         75c0d8e8  ffffff60  
         75c0d8ec  40106378  
    #06  75c0d8f0  7d038bb0  [anon:libc_malloc]
         75c0d8f4  400c9733  /system/lib/libc.so (dlfree+1226)
    #07  75c0d8f8  40102000  /system/lib/libc.so
         75c0d8fc  7d96a148  [anon:libc_malloc]
         75c0d900  00000000  
         75c0d904  77dc6b00  [anon:libc_malloc]
         75c0d908  759d4d33  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so
         75c0d90c  400c5c55  /system/lib/libc.so (free+12)
    #08  75c0d910  75ad4134  
         75c0d914  75965890  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so
    #09  75c0d918  7d96a138  [anon:libc_malloc]
         75c0d91c  00000000  
         75c0d920  7d96a138  [anon:libc_malloc]
         75c0d924  756454bb  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (std::_Rb_tree<std::string, std::string, std::_Identity<std::string>, std::lessstd::string, std::allocatorstd::string >::_M_erase(std::_Rb_tree_nodestd::string*)+26)
    #10  75c0d928  77dc6b00  [anon:libc_malloc]
         75c0d92c  00000000  
         75c0d930  00000000  
         75c0d934  756455d5  /data/app-lib/com.chunbai.xueyu3.xxxx.yyyy-1/libgame.so (cocos2d::CCSpriteFrameCache::removeUnusedSpriteFrames()+112)
    #11  75c0d938  00000001  
         75c0d93c  00000001

**Comment by kequanJiang** [comment]
请问你最后是怎么解决的？
