### ISSUE TITLE
TTFLabel 系统字体描边异常

### ISSUE THREAD

**Issue by BorgLee** [chukong/quick-cocos2d-x#515]
根据cocos2d-x反馈。需要将display.newTTFLabel 这个方法中的
```javascript
if label then
    label:setColor(color)
    if x and y then label:setPosition(x, y) end
end
```
需要将label:setColor(color) 改为 label:setTextColor(color) 否则描边会有问题。

链接在这里：
https://github.com/cocos2d/cocos2d-x/issues/9782#event-220754877

**Comment by htlxyz** [comment]
感谢反馈

fixed
https://github.com/dualface/v3quick/pull/400

PS. V3的issue可以提到V3的仓库中

**Comment by BorgLee** [comment]
我后面又测试了下 好像直接改成setTextColor 使用 cc.Label.createWithTTF 创建的Label会有问题。需要根据不同的Label来使用不同的设置颜色的方法。。。

**Comment by htlxyz** [comment]
@BorgLee 感谢你的再次反馈

https://github.com/dualface/v3quick/pull/401

**Comment by H-Sola** [comment]
多谢分享.
