### ISSUE TITLE
CCHTTPRequest 状态返回错误

### ISSUE THREAD

**Issue by liu178443039** [chukong/quick-cocos2d-x#524]
CCHTTPRequest的getErrorCode()  正常情况下返回的不是0 ，而是200，应该状态码乱了。

**Comment by zrong** [comment]
这个问题我也碰到了。
在android下面返回是 200，但win32和mac下都是0。

**Comment by zrong** [comment]
quick3也有同样问题。

**Comment by htlxyz** [comment]
android上用的是java http,非curl,这里分平台处理下吧

**Comment by a115379624** [comment]
CCHTTPRequestAndroid实在蛋疼，能否做个开关呢？其实很多人curl库还是要用的，做个开关，需要更小模块去curl库的人自己打开
