### ISSUE TITLE
ByteArrayVarint.lua 中关于bit部分成员调用的问题

### ISSUE THREAD

**Issue by fly614** [chukong/quick-cocos2d-x#525]
ByteArrayVarint.lua中的bit.rshift  、bit.lshift   应该为 bit.brshift.   bit.blshift.
还不太会用 git修改，希望看到的人改一下

**Comment by zrong** [comment]
bit.rshift 这种语法，是基于 luajit 中的 BitOp 库：http://bitop.luajit.org/

因为目前暂时禁用了 luajit ，因此改用了 pure lua 实现的 bit 库：
https://github.com/chukong/quick-cocos2d-x/blob/master/framework/cc/utils/bit.lua

建议修改 bit 库。

2015-02-27 0:34 GMT+08:00 fly_614 <notifications@github.com>:

> ByteArrayVarint.lua中的bit.rshift 、bit.lshift 应该为 bit.brshift. bit.blshift.
> 还不太会用 git修改，希望看到的人改一下
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chukong/quick-cocos2d-x/issues/525>.
>



-- 
============================
曾嵘/Jacky Tsang
Blog:http://zengrong.net

**Comment by fly614** [comment]
thanks
