### ISSUE TITLE
quick2.2.6 Android HTTP POST 汉字服务器收到乱码

### ISSUE THREAD

**Issue by wland** [chukong/quick-cocos2d-x#530]
升级到2.2.6 Android HTTP  POST带中文的数据，服务器端出现乱码，（客户端，服务端协定均为UTF-8编码）

2.2.5 版本未遇到。IOS,Windows未出现。

**Comment by wland** [comment]
刚用GET试了一下，和POST相同的结果。

**Comment by lidashuang** [comment]
2.2.6的http库有问题
