### ISSUE TITLE
quick3.3 GLProgramState 传递参数时会报错

### ISSUE THREAD

**Issue by ChenRenault** [chukong/quick-cocos2d-x#533]
比如传递浮点数：
error:
     cc.GLProgramState:setUniformFloat argument #2 is 'string'; 'number' expected.

但是会有效果，只是会报错。

**Comment by regeditms** [comment]
我也遇到,手动的 把绑定内的函数 内容调换下,先读取 string int 就不会了.

**Comment by ChenRenault** [comment]
@ZocaloFocus 
感谢您。
