### ISSUE TITLE
点击 新建项目 出现 coming soon

### ISSUE THREAD

**Issue by YagamiSaki** [chukong/quick-cocos2d-x#541]
最新版本还不能新建项目吗？

**Comment by SunLightJuly** [comment]
2.x版本的player不再作修改，请使用命令行工具创建工程。

**Comment by YagamiSaki** [comment]
好的，已了解。谢谢~





在2015年08月31 00时44分, "SunLightJuly"<notifications@github.com>写道:



2.x版本的player不再作修改，请使用命令行工具创建工程。
