### ISSUE TITLE
addNodeEventListener报错了

### ISSUE THREAD

**Issue by catinred2** [chukong/quick-cocos2d-x#543]
用cocos code ide创建一个quick工程，运行报错 ：
*[LUA ERROR] [string "framework/cocos2dx/NodeEx.lua"]:243: attempt to call a nil value*
打开NodeEx.lua的243行是：
*tolua.getcfunction(self, "addNodeEventListener")(self, evt, hdl, tag, priority)*

quick-3.3/cocos code ide 1.2.0/mac osx

另，我如果新建的是cocos lua工程而不是quick工程的话，是可以运行，但是脚本里面调用addNodeEventListener会报nil value。用的framework版本是3.6

**Comment by SunLightJuly** [comment]
版本不兼容。quick 3.3请使用自带的player或者命令行工具创建工程。
另外这里是quick 2.x的库，3.x版本的问题请在3.x的库里提交。
