### ISSUE TITLE
2.2.6版本的player在El Capitan下不能编译

### ISSUE THREAD

**Issue by pop000ooo** [chukong/quick-cocos2d-x#546]
CCConfiguration.cpp：
glGetString(GL_VENDOR)值为空

操作系统El capitan，XCode7.0.1

**Comment by pgdnxu** [comment]
遇到了同样的问题。。。。。。

**Comment by yinjimmy** [comment]
Thanks for the report, fixed with c96322d2169291ba4b8d425d92af5f19c17bdad0.
